apiVersion: apps/v1
kind: Deployment
metadata:
  name: labfiles-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labfiles-server
  template:
    metadata:
      labels:
        app: labfiles-server
    spec:
      nodeSelector:
        labfiles: "true"
      containers:
        - name: myapp-container
          image: olaekdahl/labfiles-server:1.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app-volume
              mountPath: /data/myapp
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: myapp-pvc